### ISSUE TITLE
Workspace not supported?

### ISSUE THREAD

**Issue by sohaha** [AnWeber/vscode-httpyac#202]
```js
TypeError: Cannot read properties of undefined (reading 'token') at Object.userJS (account/rbac.http:12:47) at Object.CQ [as runScript] (.vscode/extensions/anweber.vscode-httpyac-6.5.1/dist/extension.js:190:2187) at d_r.executeScriptData (.vscode/extensions/anweber.vscode-httpyac-6.5.1/dist/extension.js:187:44706) at d_r.processOnResponse (.vscode/extensions/anweber.vscode-httpyac-6.5.1/dist/extension.js:187:44620) at processTicksAndRejections (node:internal/process/task_queues:96:5) at ZZ.trigger (.vscode/extensions/anweber.vscode-httpyac-6.5.1/dist/extension.js:1:5158) at jvr (.vscode/extensions/anweber.vscode-httpyac-6.5.1/dist/extension.js:186:23237) at Object.action (.vscode/extensions/anweber.vscode-httpyac-6.5.1/dist/extension.js:186:21643) at ZZ.trigger

```

**Comment by AnWeber** [comment]
@sohaha What do you mean with support of workspaces? I use http files in Workspaces and it works fine. How is your setup?

**Comment by sohaha** [comment]
It seems that only the first folder in the workspace is supported.


for example:
```
dir1
  1.http // normal

dir2
  1.http // error
```

**Comment by AnWeber** [comment]
@sohaha  your script needs a token, where is this token defined?

**Comment by sohaha** [comment]
sorry forgot this,

http-client.private.env.json is dir2

```json
{
  "dev": {
    "host": "http://127.0.0.1:8181",
    "token": "666"
  }
}


```

**Comment by AnWeber** [comment]
@sohaha can you please provide a complete example. Could not reproduce.

**Comment by sohaha** [comment]
There is no such problem at present, thank you for providing such a useful extension
