### ISSUE TITLE
Log errors on environment reset

### ISSUE THREAD

**Issue by alekdavisintel** [AnWeber/vscode-httpyac#296]
When I run the `httpYac: Reset Environments` command, the `httpyac - Log` shows the following errors:
```
ERROR: delete of uri vscode-userdata:/c%3A/Users/MYUSERNAME/AppData/Roaming/Code/User/globalStorage/anweber.vscode-httpyac/.httpyac/sourcesJson.13db5583.json failed
EntryNotFound (FileSystemError) - Unable to delete nonexistent file 'vscode-userdata:/c:/Users/MYUSERNAME/AppData/Roaming/Code/User/globalStorage/anweber.vscode-httpyac/.httpyac/sourcesJson.13db5583.json'
EntryNotFound (FileSystemError): Unable to delete nonexistent file 'vscode-userdata:/c:/Users/MYUSERNAME/AppData/Roaming/Code/User/globalStorage/anweber.vscode-httpyac/.httpyac/sourcesJson.13db5583.json'
	at y.e (c:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:6797)
	at Object.delete (c:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:5035)
	at async hF.clear (c:\Users\MYUSERNAME\.vscode\extensions\anweber.vscode-httpyac-6.14.0\dist\extension.js:345:20805)
	at async WN.clear (c:\Users\MYUSERNAME\.vscode\extensions\anweber.vscode-httpyac-6.14.0\dist\extension.js:346:5334)
	at async Bh.reset (c:\Users\MYUSERNAME\.vscode\extensions\anweber.vscode-httpyac-6.14.0\dist\extension.js:345:49385)
	at async r.h (c:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:189457)
ERROR: delete of uri vscode-userdata:/c%3A/Users/MYUSERNAME/AppData/Roaming/Code/User/globalStorage/anweber.vscode-httpyac/.httpyac/response failed
EntryNotFound (FileSystemError) - Unable to delete nonexistent file 'vscode-userdata:/c:/Users/MYUSERNAME/AppData/Roaming/Code/User/globalStorage/anweber.vscode-httpyac/.httpyac/response'
EntryNotFound (FileSystemError): Unable to delete nonexistent file 'vscode-userdata:/c:/Users/MYUSERNAME/AppData/Roaming/Code/User/globalStorage/anweber.vscode-httpyac/.httpyac/response'
	at y.e (c:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:6797)
	at Object.delete (c:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:5035)
	at async hF.clear (c:\Users\MYUSERNAME\.vscode\extensions\anweber.vscode-httpyac-6.14.0\dist\extension.js:345:20805)
	at async WN.clear (c:\Users\MYUSERNAME\.vscode\extensions\anweber.vscode-httpyac-6.14.0\dist\extension.js:346:5334)
	at async Bh.reset (c:\Users\MYUSERNAME\.vscode\extensions\anweber.vscode-httpyac-6.14.0\dist\extension.js:345:49385)
	at async r.h (c:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:189457)
```

**Comment by AnWeber** [comment]
I have to remove the log message. It's just confusing. The background is that I don't want to use too much memory for the history function, so I save the responses on the hard disk in a temp folder. With `reset` I want to clean up the store, but I do this more or less twice. On the one hand, every response is removed from the history and the file is also deleted. In addition, I simply delete the entire folder directly to ensure that no files are left behind. Previously the order was different, but I seem to have reversed it at some point. And now I'm just trying to delete files that don't exist.
I have accepted the message, but yes, it would be clean to avoid it.

**Comment by AnWeber** [comment]
fixed with next release
