### ISSUE TITLE
Variables Defined Globally Not Recognized in Subsequent Requests After the First One

### ISSUE THREAD

**Issue by vupan** [AnWeber/vscode-httpyac#344]
I am encountering an issue with the httpyac extension in VS Code where variables defined globally (@WebAPIDemo_HostAddress) are not recognized in any requests following the first one. When I attempt to send a request that uses these variables after the initial request, I receive a ReferenceError indicating that the variable is not defined. The error message is as follows:
> ReferenceError: WebAPIDemo_HostAddress is not defined at Object.userJS (c:\Users\wupan\Code\WebAPIDemo\WebAPIDemo.http:8:20) at XY (c:\Users\wupan\.vscode\extensions\anweber.vscode-httpyac-6.16.4\dist\extension.js:279:2732) at K4e (c:\Users\wupan\.vscode\extensions\anweber.vscode-httpyac-6.16.4\dist\extension.js:279:3334) at c:\Users\wupan\.vscode\extensions\anweber.vscode-httpyac-6.16.4\dist\extension.js:279:6641 at sf (c:\Users\wupan\.vscode\extensions\anweber.vscode-httpyac-6.16.4\dist\extension.js:162:36738) at Object.Ser [as action] (c:\Users\wupan\.vscode\extensions\anweber.vscode-httpyac-6.16.4\dist\extension.js:279:6606) at hNe.trigger (c:\Users\wupan\.vscode\extensions\anweber.vscode-httpyac-6.16.4\dist\extension.js:27:3362) at wo (c:\Users\wupan\.vscode\extensions\anweber.vscode-httpyac-6.16.4\dist\extension.js:162:19245) at Object.xYt [as action] (c:\Users\wupan\.vscode\extensions\anweber.vscode-httpyac-6.16.4\dist\extension.js:162:78505) ...

The issue persists unless I execute the first GET request, which seems to initialize the variables. However, if I reload the VS Code window, the problem reoccurs.
Here is the content of my request file:
```
@WebAPIDemo_HostAddress = http://localhost:5017

GET {{WebAPIDemo_HostAddress}}/shirts/
Accept: application/json

###
GET {{WebAPIDemo_HostAddress}}/shirts/1
```
### Steps to Reproduce:

1. Open VS Code.

2. Ensure the httpyac extension is installed and enabled.

3. Create or open an .http file with the content provided above.

4.  Attempt to send the second GET request without sending the first one.

5.  Observe the ReferenceError.

### Environment:

- VS Code Version:
    版本: 1.95.3
    提交: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
    日期: 2024-11-13T14:50:04.152Z
    浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.95.3 Chrome/128.0.6613.186         Electron/32.2.1 Safari/537.36

- Httpyac Extension Version: 6.16.4
- OS:
    版本	Windows 11 专业版
    版本号	24H2
    安装日期	‎2024/‎11/‎10
    操作系统版本	26100.2454
    体验	Windows 功能体验包 1000.26100.36.0

**Comment by AnWeber** [comment]
@vupan sorry for the late response. Your variable is only defined for the first region. It is not global. A valid global region has no name or request in it. You need to explicitly separate these regions with `###`

```
@WebAPIDemo_HostAddress = http://localhost:5017
### <----
GET {{WebAPIDemo_HostAddress}}/shirts/
Accept: application/json

###
GET {{WebAPIDemo_HostAddress}}/shirts/1
```
