### ISSUE TITLE
global Variable undefined

### ISSUE THREAD

**Issue by AnWeber** [AnWeber/vscode-httpyac#48]
### Discussed in https://github.com/AnWeber/vscode-httpyac/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **gerukin** July  6, 2021</sup>
Hi, I'm new to `httpyac`. I currently use `rest-client` and `Postman`. The extension and runner look promising, congrats!, but somehow I cannot make anything work.

I'm using the latest general availability vscode (Mac) and have installed both the cli and the extension. I opened a new folder with just this one file:
```
@url = http://www.google.com

### Test
{{url}}
```

Clicking `send` gets me this:

```
ERROR: js: exports.$result = (url);
ERROR: ReferenceError - url is not defined
ReferenceError: url is not defined
	at Object.userJS (/Users/gerukin/dev/http-test/test.http:4:86)
	at Object.<anonymous> (/Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:37501)
	at Generator.next (<anonymous>)
	at /Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:36506
	at new Promise (<anonymous>)
	at s (/Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:36251)
	at Object.g (/Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:36785)
	at t.JavascriptVariableReplacer.<anonymous> (/Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:143455)
	at Generator.next (<anonymous>)
	at /Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:142841
	at new Promise (<anonymous>)
	at r (/Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:142586)
	at t.JavascriptVariableReplacer.replace (/Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:143089)
	at Object.<anonymous> (/Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:46841)
	at Generator.next (<anonymous>)
	at s (/Users/gerukin/.vscode/extensions/anweber.vscode-httpyac-2.18.0/dist/extension.js:587:46333)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This works though:
```
### Test
@url = http://www.google.com
{{url}}
```

But my understanding is that those variables are in a global scope and should be available to all requests. What am I doing wrong?</div>

**Comment by AnWeber** [comment]
The cause was an incorrect setting of an If condition for the check whether the progress bar should be displayed. This change was included in the previous version for httpbook and unfortunately caused an error in vscode-httpyac.
