### ISSUE TITLE
How to parse the response json file, then set the value to a variable?

### ISSUE THREAD

**Issue by shenngw1127** [AnWeber/vscode-httpyac#59]
i want to following steps

1. login with username and password
2. then parse the json body in response, and set it to a variable like 'harbor_auth_token'
3. use the variable send another request

first step response like this

```
{
  "token": "AuUefgg",
  "access_token": "",
  "expires_in": 1800,
  "issued_at": "2021-07-29T04:56:53Z"
}
```

example.http file like this

```
### login get token
GET https://{{harborHost}}/service/token?account={{harborUsername}}&service=harbor-registry
Authorization: Basic {{harborUsername}}:{{harborPassword}}
Accept: application/json

> {% 
    client.global.set("harbor_auth_token", response.body.json.token); 
    console.log(response.body.json.token); 
%}

### get repositories
GET https://{{harborHost}}/api/v2.0/projects/3/repositories
Authorization: Bearer {{harbor_auth_token}}
Accept: application/json
```

then i push the "send all", but got an error

```
TypeError: Cannot read property 'token' of undefined
	at Object.userJS (/Users/ws/workspace/quickapp/QuickAppServer/quickapp-server/src/test/http/test/harbor.http:7:143)
	at Object.<anonymous> (/Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:37658)
	at Generator.next (<anonymous>)
	at /Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:36665
	at new Promise (<anonymous>)
	at s (/Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:36410)
	at Object.y [as executeScript] (/Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:36934)
	at t.IntellijAction.<anonymous> (/Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:35111)
	at Generator.next (<anonymous>)
	at /Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:34475
	at new Promise (<anonymous>)
	at s (/Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:34220)
	at t.IntellijAction.process (/Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:34725)
	at /Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:128005
	at Generator.next (<anonymous>)
	at s (/Users/ws/.vscode/extensions/anweber.vscode-httpyac-2.21.1/dist/extension.js:511:125859)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

how could i modify the right .http file?

**Comment by AnWeber** [comment]
Do you need to be Intellij compatible? If not, then the following
```
### login get token
# @name login
GET https://{{harborHost}}/service/token?account={{harborUsername}}&service=harbor-registry
Authorization: Basic {{harborUsername}}:{{harborPassword}}
Accept: application/json

### get repositories
GET https://{{harborHost}}/api/v2.0/projects/3/repositories
Authorization: Bearer {{login.response.parsedBody.json.token}}
Accept: application/json
```

If yes, then the body must be converted to JSON first.
```
### login get token
GET https://{{harborHost}}/service/token?account={{harborUsername}}&service=harbor-registry
Authorization: Basic {{harborUsername}}:{{harborPassword}}
Accept: application/json

> {% 
    client.global.set("harbor_auth_token", JSON.parse(response.body).json.token); 
    console.log(response.body.json.token); 
%}

### get repositories
GET https://{{harborHost}}/api/v2.0/projects/3/repositories
Authorization: Bearer {{harbor_auth_token}}
Accept: application/json

```

**Comment by sdasda7777** [comment]
Hi, I just thought I would mention that the code above seems to be outdated, to save time of anyone who might have stumbled upon this issue. The properties of the response seem to be available under properties of the request, so what worked for me is actually something like this:
```httpyac
### login get token
# @name login
GET https://{{harborHost}}/service/token?account={{harborUsername}}&service=harbor-registry
Authorization: Basic {{harborUsername}}:{{harborPassword}}
Accept: application/json

### get repositories
GET https://{{harborHost}}/api/v2.0/projects/3/repositories
Authorization: Bearer {{login.token}}
Accept: application/json
```
